<?php
$configFile = 'config.php';
$config = include $configFile;

$message = "";

// Handle form submission to update config
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST['save_config'])) {
    $newDashboardLogFile = $_POST['gateway_log_file'] ?? $config['gateway_log_file'];
    $newNodeConfigFile = $_POST['gateway_config_file'] ?? $config['gateway_config_file'];
    $newHostfile = $_POST['hostfile'] ?? $config['hostfile'];

    // Safely escape input for use in PHP code
    $newDashboardLogFile = addslashes($newDashboardLogFile);
    $newNodeConfigFile = addslashes($newNodeConfigFile);
    $newHostfile = addslashes($newHostfile);

    $newConfig = <<<PHP
<?php
return [
    'gateway_log_file' => '$newDashboardLogFile',
    'gateway_config_file' => '$newNodeConfigFile',
    'hostfile' => '$newHostfile',
];
PHP;

    // Write new configuration
    file_put_contents($configFile, $newConfig);

    // Invalidate PHP opcode cache
    if (function_exists('opcache_invalidate')) {
        opcache_invalidate($configFile, true);
    }

    // Re-load updated config
    $config = include $configFile;
    $message = "Configuration updated successfully.";

    } elseif (isset($_POST['run_command'])) {
        $selectedCommand = $_POST['run_command'];

        switch ($selectedCommand) {
            case 'status':
                $command = 'systemctl status m17-gateway.service';
                break;
            case 'start':
                $command = 'systemctl start m17-gateway.service';
                break;
            case 'stop':
                $command = 'systemctl stop m17-gateway.service';
                break;
            case 'restart':
                $command = 'systemctl restart m17-gateway.service';
                break;
            case 'id':
                $command = 'id';
                break;
            case 'log':
                $command = 'tail -n 30 '.htmlspecialchars($config['gateway_log_file']);
                break;
            default:
                $command = '';
        }

        if ($command) {
            $commandOutput = shell_exec($command);
        }
    }
}
?>
<!DOCTYPE html>
<html>
<?php include 'header.php';?>

<?php if (!empty($message)) echo "<div class='message'>$message</div>"; ?>

<div class="config-panel-container">
<div class="config-panel-wrapper">

<form method="post">
    <table id="config_panel">

    <tr>
        <th colspan="3">Dashboard Configuration</th>
    </tr>
    <tr>
        <td>M17 Gateway Log File</td>
        <td><input type="text" id="gateway_log_file" name="gateway_log_file" value="<?= htmlspecialchars($config['gateway_log_file']) ?>" required></td>
        <td>Location of the log file generated by m17-gateway</td>
    </tr>
    <tr>
        <td>M17 Gateway Configuration File</td>
        <td><input type="text" id="gateway_config_file" name="gateway_config_file" value="<?= htmlspecialchars($config['gateway_config_file']) ?>" required></td>
        <td>Location of the m17-gateway configuration file</td>
    </tr>
    <tr>
        <td>Hostfile</td>
        <td><input type="text" id="hostfile" name="hostfile" value="<?= htmlspecialchars($config['hostfile']) ?>" required></td>
        <td>Location of the hosts file whch contains all the M17 reflectors</td>
    </tr>
    <tr>
        <th colspan="3"><input name="save_config" type="submit" value="Save Configuration"></th>
    </tr>
    </table>
</form>
</div>


<div class="config-panel-wrapper">
<form method="post" style="display: flex; gap: 10px; flex-wrap: wrap;">
    <table id="config_panel">
    <tr>
        <th colspan="2">Execute Commands</th>
    </tr>
    <tr>
        <td>M17 Gateway Control</td>
        <td><button type="submit" name="run_command" value="status">Status</button>
        <button type="submit" name="run_command" value="start">Sart</button>
        <button type="submit" name="run_command" value="stop">Stop</button>
        <button type="submit" name="run_command" value="restart">Restart</button></td>
    </tr>
    <tr>
        <td>M17 Gateway Log</td>
        <td><button type="submit" name="run_command" value="log">Show Log</button></td>
    </tr>
    <tr>
        <td>id</td>
        <td><button type="submit" name="run_command" value="id">ID</button></td>
    </tr>
    </table>
</form>
</div>
</div>

<?php if (!empty($commandOutput)): ?>
    <h3>Command Output:</h3>
    <pre><?= htmlspecialchars($commandOutput) ?></pre>
<?php endif; ?>
<?php include 'footer.php';?>
</body>
</html>
