<?php
$configFile = 'config.php';
$config = include $configFile;

$message = "";

// Handle form submission to update config
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST['save_config'])) {
    $newDashboardLogFile = $_POST['gateway_log_file'] ?? $config['gateway_log_file'];
    $newNodeConfigFile = $_POST['gateway_config_file'] ?? $config['gateway_config_file'];
    $newMaxLines = $_POST['maxlines'] ?? $config['maxlines'];
    $newTZ = $_POST['timezone'] ?? $config['timezone'];

    // Safely escape input for use in PHP code
    $newDashboardLogFile = addslashes($newDashboardLogFile);
    $newNodeConfigFile = addslashes($newNodeConfigFile);
    $newMaxLines = addslashes($newMaxLines);
    $newTZ = addslashes($newTZ);

    $newConfig = <<<PHP
<?php
return [
    'gateway_log_file' => '$newDashboardLogFile',
    'gateway_config_file' => '$newNodeConfigFile',
    'hostfile' => 'files/M17Hosts.txt',
    'maxlines' => '$newMaxLines',
    'timezone' => '$newTZ',
];
PHP;


    // Write new configuration
    file_put_contents($configFile, $newConfig);

    // Invalidate PHP opcode cache
    if (function_exists('opcache_invalidate')) {
        opcache_invalidate($configFile, true);
    }

    // Re-load updated config
    $config = include $configFile;
    $message = "Configuration updated successfully.";

    } elseif (isset($_POST['run_command'])) {
        $selectedCommand = $_POST['run_command'];

        switch ($selectedCommand) {
            case 'status':
                $command = '/usr/bin/systemctl status m17-gateway.service';
                break;
            case 'start':
                $command = '/usr/bin/systemctl start m17-gateway.service';
                break;
            case 'stop':
                $command = '/usr/bin/systemctl stop m17-gateway.service';
                break;
            case 'restart':
                $command = '/usr/bin/systemctl restart m17-gateway.service';
                break;
            case 'showhostfile':
                $command = '/usr/bin/cat files/M17Hosts.txt';
                break;
            case 'updatehostfile':
                $command = '/usr/bin/curl https://hostfiles.refcheck.radio/M17Hosts.txt -o files/M17Hosts.txt';
                break;
            case 'log':
                $command = '/usr/bin/tail -n 30 '.htmlspecialchars($config['gateway_log_file']);
                break;
            default:
                $command = '';
        }

        if ($command) {
            $commandOutput = shell_exec($command);
        }
    }
}

// Get all time zones
//$timezones = DateTimeZone::listIdentifiers(DateTimeZone::ALL);
$timezones = DateTimeZone::listIdentifiers();
$timezone = $config['timezone'];

?>
<!DOCTYPE html>
<html>
<?php include 'header.php';?>

<?php if (!empty($message)) echo "<div class='message'>$message</div>"; ?>

<div class="config-panel-container">
<div class="config-panel-wrapper">

<form method="post">
    <table id="config_panel">

    <tr>
        <th colspan="3">Dashboard Configuration</th>
    </tr>
    <tr>
        <td>M17 Gateway Log File</td>
        <td><input type="text" id="gateway_log_file" name="gateway_log_file" value="<?= htmlspecialchars($config['gateway_log_file']) ?>" required></td>
        <td>Location of the log file generated by m17-gateway</td>
    </tr>
    <tr>
        <td>M17 Gateway Configuration File</td>
        <td><input type="text" id="gateway_config_file" name="gateway_config_file" value="<?= htmlspecialchars($config['gateway_config_file']) ?>" required></td>
        <td>Location of the m17-gateway configuration file</td>
    </tr>
    <tr>
        <td>Max. Number of Lines</td>
        <td><input type="text" id="maxlines" name="maxlines" value="<?= htmlspecialchars($config['maxlines']) ?>" required></td>
        <td>The maximum number of lines displayed in the "Last Heard" table of the dashboard</td>
    </tr>
    <tr>
        <td>Timezone</td>
        <td>
    <select name="timezone" id="timezone">
        <?php foreach ($timezones as $tz): ?>
            <option value="<?= htmlspecialchars($tz) ?>" <?= $tz === $timezone ? 'selected' : '' ?>>
                <?= htmlspecialchars($tz) ?>
            </option>
        <?php endforeach; ?>
    </select>
	</tz>
        <td>Timezone to be used in the dashboard</td>
    </tr>
    <tr>
        <th colspan="3"><input name="save_config" type="submit" value="Save Configuration"></th>
    </tr>
    </table>
</form>
</div>


<div class="config-panel-wrapper">
<form method="post" style="display: flex; gap: 10px; flex-wrap: wrap;">
    <table id="config_panel">
    <tr>
        <th colspan="2">Execute Commands</th>
    </tr>
    <tr>
        <td>M17 Gateway Service</td>
        <td><button type="submit" name="run_command" value="status">Status</button>
        <button type="submit" name="run_command" value="start">Start</button>
        <button type="submit" name="run_command" value="stop">Stop</button>
        <button type="submit" name="run_command" value="restart">Restart</button></td>
    </tr>
    <tr>
        <td>M17 Gateway Raw Log</td>
        <td><button type="submit" name="run_command" value="log">Show Log</button></td>
    </tr>
    <tr>
        <td>Show Hostfile</td>
        <td><button type="submit" name="run_command" value="showhostfile">Show Hostfile</button></td>
    </tr>
    <tr>
        <td>Update Hostfile</td>
        <td><button type="submit" name="run_command" value="updatehostfile">Update Hostfile</button></td>
    </tr>
    </table>
</form>
</div>
</div>

<?php if (!empty($commandOutput)): ?>
    <h3>Command Output:</h3>
    <pre><?= htmlspecialchars($commandOutput) ?></pre>
<?php endif; ?>
<?php include 'footer.php';?>
</body>
</html>
