<?php

include 'header.php';

?>

<!DOCTYPE html>
<html>

    <h2>Overview of the Hotspot Dashboard</h2>

    <h3>Dashboard Page</h3>
    <p>
        The <b>Dashboard</b> page provides an overview of the current status and activities of your M17 hotspot.
    </p>
    <ul>
        <li><b>Last Heard:</b> This table on the upper right displays recent transmissions received by the gateway, showing call sign, time and date, source, destination, and other details. If the Interface is <b>RF</b>, the transmission originates from a radio near your hotspot while <b>Internet</b> indicates the transmission of a remote station.</li>
        <li><b>Node Info:</b> Shows the frequencies you have configured your hotspot for RX and TX. The info is taken from the m17-gateway configuration file.</li>
        <li><b>M17 Status:</b> Shows the configured node call sign, the reflector and module your node is connected to as well as the radio status. The information, to which reflector and module your hotspot is connected to is read from log lines generated by m17-gateway. The cell's background is green when connected and red when disconnected. <b>Radio status</b> shows either <b>Listening</b> (no transmission at all), <b>RX: &lt;call sign&gt;</b> (a radio near the repeater is transmitting and the hotspot is receiving it via RF) or <b>TX: &lt;call sign&gt;</b> (a remote station is transmitting, your hotspot receives the data via the internet and transmits it via RF).</li>
        <li><b>Text Messages:</b> Shows incoming and outgoing text messages sent by your radio or remote stations.</li>
    </ul>

    <h3>Map Page</h3>
    <p>
        The <b>Map</b> page shows all M17 stations that have sent a GNSS package and therefore transmitted their location via the connected reflector. The dashboard software extracts these information from the m17-gateway log and adds a pin for each call sign to the map. If a station sends multiple locations, only the last received will be shown.
    </p>

    <h3>Gateway Config Page</h3>
    <p>
        The <b>Gateway Config</b> page allows the hotspot user to configure essential gateway parameters such as:
    </p>
    <ul>
        <li><b>General - Callsign:</b> most likely the owners call sign plus an H for Hotspot</li>
        <li><b>General - DashboardLog:</b> The full path to where m17-gateway will write its log file (default: /opt/m17/m17-gateway/dashboard.log)</li>
        <li><b>Radio - RXFrequency:</b> Set here the RX frequency of your hotspot</li>
        <li><b>Radio - TXFrequency:</b> Set here the TX frequency of your hotspot</li>
        <li><b>Radio - Power:</b> Set here the desired output power of your hotspot (default: 10)</li>
        <li><b>Radio - AFC:</b> Enable/disable the automatic frequency correction feature for your hotspot (default: 0)</li>
        <li><b>Radio - FrequencyCorr:</b> Manual frequency correction if your hotspot is not perfectly on frequency (default: 0, can be postive or negative)</li>
        <li><b>Radio - Duplex:</b> Defines if a simplex or duplex hotspot is used (default: false)</li>
        <li><b>Reflector - HostFile:</b> Location of the M17 host file. This file contains all the M17 reflectors with their IP addresses and ports (default: /opt/m17/m17-gateway/M17Hosts.txt)</li>
        <li><b>Reflector - OverrideHostFile:</b> Location of the M17 host override file. Use this fiel to add custom reflectors that are not in the official host file. (default: /opt/m17/m17-gateway/OverrideHosts.txt)</li>
        <li><b>Reflector - Name:</b> Drop down box including all M17 reflectors. Use this to set the reflector you want to connect to. (default: M-17-M17)</li>
        <li><b>Reflector - Module:</b> Drop down box including all possible modules. Use this to set the module you want to connect to. (default: C)</li>
        <li><b>Reflector - Level:</b> The log level for the m17-gateway. Impacts the verbosity but also the size of the file. (default: DEBUG)</li>
        <li><b>Reflector - Port:</b> The serial port/device which the m17-gateway uses to connect to the CC1200 hat (default: /dev/ttyAMA0)</li>
        <li><b>Reflector - Speed:</b> Baud rate used for the serial connection to the CC1200 hat (default: 460800)</li>
        <li><b>Reflector - NRSTPin:</b> (default: 21)</li>
        <li><b>Reflector - PAEnablePin:</b> (default: 18)</li>
        <li><b>Reflector - Boot0Pin:</b> (default: 20)</li>
    </ul>
    <p>
        Please note that all fields on this page are extracted from the gateway configuration file. If a new configuraation item will be added to the config file, it will show up here, too. If an item will be removed, it will disappear here.
    </p>

    <h3>Dashboard Config Page</h3>
    <p>
        The <b>Dashboard Config</b> page is used to configure the dashboard itself. Here, you can adjust:
    </p>
    <ul>
        <li><b>M17 Gateway Log File:</b> Location of the log file generated by m17-gateway. This path is relative to the document root of the underlying web server and is a symlink to the actual file (default: files/dashboard.log)</li>
        <li><b>M17 Gateway Configuration File:</b> Location of the m17-gateway configuration file. This path is relative to the document root of the underlying web server and is a symlink to the actual file (default: files/m17-gateway.ini)</li>
        <li><b>Max. Number of Lines:</b> The maximum number of lines displayed in the "Last Heard" table of the dashboard (default: 15)</li>
        <li><b>Timezone:</b> Drop down box with all possible time zones. This will change the time displayed in the dashboard's last heard list (default: UTC)</li>
        <li><b>Unit System:</b> Drop down box with 'Imperial' and 'Metric'. This will change how dates, times and others will be displayed/calculated  (default: Metric)</li>
        <li><b>Map Marker TTL:</b> Defines how many minutes after the last transmission the position of a station is still displayed on the map. (default: 43200 (30 days))</li>
    </ul>
    <p>
        You can furthermore execute a few selected operating system commands via the following buttons:
    </p>
    <ul>
        <li><b>M17 Gateway Service:</b> Start, stop, restart the m17-gateway or query its status.</li>
        <li><b>M17 Gateway Raw Log:</b> Show the raw log of m17-gateway. This is mostly used for debugging purposes.</li>
        <li><b>Show Hostfile:</b> List the M17 host file. You can check in its header if it is up to date.</li>
        <li><b>Update Hostfile:</b> Download the latest M17 host file to the hotspot.</li>
    </ul>

    <h2>FAQ</h2>
    <ul>
        <li><b>Q: How do I update the dashboard and/or m17-gateway?</b><br>
            <b>A:</b> It is highly recommended to download and execute the <a href="https://github.com/M17-Project/cc1200-hotspot-installer" target="_blank">CC1200 Hotspot Installer</a>. This script not only installs all necessary software but also updates it.</li>

        <li><b>Q: Why are some stations not showing up on the map page?</b><br>
            <b>A:</b> Stations need to send their location via the M17 network in order to appear on the map. Only radios with a GPS module and a firmware that supports this can send this data out of the box.<br>

        <li><b>Q: How do I switch to another reflector or module?</b><br>
            <b>A:</b> Go to the "Gateway Config" page, select the new reflector and module via the two drop down boxes, save the changes and restart m17-gateway.</li>

        <li><b>Q: How can I restart the M17 Gateway from the command line?</b><br>
            <b>A:</b> <i>sudo systemctl start/stop/restart m17-gateway.service</i></li>

        <li><b>Q: Where are all the files located that have been installed by the cc1200-hotspot-installer?</b><br>
            <b>A:</b> You will find these files in <i>/opt/m17/</i></li>

        <li><b>Q: How do I contribute to the project?</b><br>
            <b>A:</b> Fork the repository on GitHub, create a feature branch, and submit a pull request. Contributions are welcome!</li>
    </ul>

    <h2>Need more Help?</h2>
    <p>
        <b>If you need more help, please <a href="https://m17project.org/contact/" target="_blank">contact us</a>. We are here to help!</b>
    </p>

    <h2>Links</h2>
    <ul>
        <li><a href="https://m17project.org" target="_blank">M17 Project Homepage</a></li>
        <li><a href="https://wiki.m17project.org" target="_blank">M17 Project Wiki</a></li>
        <li><a href="https://github.com/M17-Project/rpi-dashboard" target="_blank">M17 Dashboard GitHub Repository</a></li>
        <li><a href="https://github.com/M17-Project" target="_blank">M17 Project GitHub Organization</a></li>
    </ul>
</div>
<?php include 'footer.php';?>

</body>
</html>
